---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beethoven-deployment
  labels:
    app: beethoven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beethoven
  template:
    metadata:
      labels:
        app: beethoven
    spec:
      containers:
        - name: nginx
          image: docker.io/blindmuaddib/beethoven:latest
          ports:
            - containerPort: 80
