---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-data-pv
  labels:
    pv: shared-data-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /containers/MTD/shared-data
