---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musictranslator-ingress
spec:
  rules:
  - host: musictranslator.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - host: www.musictranslator.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  ingressClassName: nginx
  tls:
  - hosts:
      - musictranslator.org
      - www.musictranslator.org
    secretName: tls-cert
