---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musictranslator-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-body-size: "60m"
spec:
  rules:
  - host: musictranslator.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      # - path: /translate
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: translator-service
      #       port:
      #         number: 20005
  - host: www.musictranslator.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      # - path: /translate
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: translator-service
      #       port:
      #         number: 20005
  ingressClassName: nginx
  tls:
  - hosts:
      - musictranslator.org
      - www.musictranslator.org
    secretName: tls-cert
