---
apiVersion: v1
kind: Service
metadata:
  name: mfa-service
spec:
  selector:
    app: mfa-wrapper
  ports:
    - protocol: TCP
      port: 24725
      targetPort: 24725
      nodePort: 31000
  type: NodePort
