---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    error_log /var/log/nginx/error.log warn;
    pid       /var/log/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log  main;

      sendfile      on;

      keepalive_timeout  65;
      client_max_body_size 60M;

      server {
        listen 80;
        server_name musictranslator.org www.musictranslator.org;
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        server_name musictranslator.org www.musictranslator.org;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        # Add HSTS header after site works over HTTPS
        # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

        root /usr/share/nginx/html;
        index index.html;

        location / {
          # Try to serve the requested file, then directory, then fallback to index.html
          try_files $uri $uri/ /index.html;
        }

        # Location block to proxy API requests to the Flask backend
        location /translate {
          proxy_pass http://translator-service:20005;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          # Increase timeouts for long processing tasks
          proxy_connect_timeout 60s;
          proxy_send_timeout    900s;
          proxy_read_timeout    900s;
        }
      }
    }
