---
apiVersion: v1
kind: Service
metadata:
  name: demucs-service
spec:
  selector:
    app: demucs-wrapper
  ports:
    - protocol: TCP
      port: 22227
      targetPort: 22227
      nodePort: 30080
  type: NodePort
