---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - name: music-translator-container
          image: localhost/music-translator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20005
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "8Gi"

