apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /containers/MTD/pv-audio
