apiVersion: apps/v1
kind: Deployment
metadata:
  name: spleeter-deployment
  labels:
    app: spleeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spleeter
  template:
    metadata:
      labels:
        app: spleeter
    spec:
      containers:
        - name: spleeter-containers
          image: deezer/spleeter:latest
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
          volumeMounds:
          - name: audio-volume
            mountPath: /input_output
        volumes:
        - name: audio-volume
          persistentVolumeClaim:
            claimName: audio-pvc
